### ISSUE TITLE
新版本QQNT无法更新插件了

### ISSUE THREAD

**Issue by SoudayoWwww** [xinyihl/LiteLoaderQQNT-PluginInstaller#10]
![image](https://github.com/xinyihl/LiteLoaderQQNT-PluginInstaller/assets/52328223/4672f666-fc6f-46bc-8f59-56c184aa9a6f)

![image](https://github.com/xinyihl/LiteLoaderQQNT-PluginInstaller/assets/52328223/998c005f-3e5c-43e3-89ad-517f4854f3d9)

![image](https://github.com/xinyihl/LiteLoaderQQNT-PluginInstaller/assets/52328223/44ed52f6-9749-43d0-8600-ee88d4b0f058)
点更新没有像以前那样弹窗出来了

**Comment by xinyihl** [comment]
能否用控制台启动并把日志发一下

**Comment by SoudayoWwww** [comment]
> 能否用控制台启动并把日志发一下

不好意思我不是开发者，不知道怎么控制台启动，请问有说明文档看吗

**Comment by xinyihl** [comment]
> > 能否用控制台启动并把日志发一下
> 
> 不好意思我不是开发者，不知道怎么控制台启动，请问有说明文档看吗

使用cmd在qq文件夹执行 qq.exe --enable-logging
https://liteloaderqqnt.github.io/docs/introduction.html#%E8%B0%83%E8%AF%95%E4%BB%A3%E7%A0%81

**Comment by SoudayoWwww** [comment]
[log.txt](https://github.com/user-attachments/files/16145005/log.txt)

**Comment by xinyihl** [comment]
在旧版本无法使用之前我可能不会往高版本升级
你可以将这一项修改成true试试
https://github.com/xinyihl/LiteLoaderQQNT-PluginInstaller/blob/a6ee129c8289f1158e8222376143da8207f5fad2/src/main.js#L71

**Comment by SoudayoWwww** [comment]
成功解决，谢谢
