### ISSUE TITLE
安装插件后无法打开QQ

### ISSUE THREAD

**Issue by minecraft4668** [xinyihl/LiteLoaderQQNT-PluginInstaller#11]
如题

**Comment by xinyihl** [comment]
请给出qq版本，加载器版本等等，以及log。否则我无法帮助你

**Comment by minecraft4668** [comment]
QQ版本：
![QQ_1720712942376](https://github.com/xinyihl/LiteLoaderQQNT-PluginInstaller/assets/132268400/7c960475-b6ae-4b31-9242-37af73a140a4)
加载器参数：
![QQ_1720712915857](https://github.com/xinyihl/LiteLoaderQQNT-PluginInstaller/assets/132268400/24dfb3ad-47b5-4c22-8101-f7d1a35efd2b)
log不知道在哪里找，如果你知道请给我路径，谢谢。

**Comment by xinyihl** [comment]
使用cmd在qq文件夹执行 qq.exe --enable-logging
https://liteloaderqqnt.github.io/docs/introduction.html#%E8%B0%83%E8%AF%95%E4%BB%A3%E7%A0%81

**Comment by minecraft4668** [comment]
![image](https://github.com/user-attachments/assets/192a5899-9c67-4169-a9e9-17ae1cec7488)
 日志在这里终止，不在运行

**Comment by minecraft4668** [comment]
而在我卸载插件后
![QQ_1721183320389](https://github.com/user-attachments/assets/1c5257b7-1672-4008-a25e-d37b3fc3e679)
QQ就能正常运行

**Comment by xinyihl** [comment]
我这边测试了没有问题，应该是其他插件导致的无法启动，请你单独安装本插件试试

**Comment by minecraft4668** [comment]
![image](https://github.com/user-attachments/assets/bb7b50e1-1da3-4309-801b-e653bdadd700)
当我把其他插件全部卸载后，他又给我弹出了这个报错

**Comment by xinyihl** [comment]
个人问题，请下载releases
