### ISSUE TITLE
部分插件无法下载?

### ISSUE THREAD

**Issue by raging-flames** [xinyihl/LiteLoaderQQNT-PluginInstaller#12]
![image](https://github.com/user-attachments/assets/206186c7-22f0-4262-84da-e461cde2d725)
![image](https://github.com/user-attachments/assets/fadf49be-3296-49c0-9468-f337f325ca69)
插件是https://github.com/qianxuu/LiteLoaderQQNT-Plugin-Demo-Mode/blob/main/manifest.json
下载了一些插件，唯独这个安装按键是灰色的

**Comment by xinyihl** [comment]
fix  https://github.com/xinyihl/LiteLoaderQQNT-PluginInstaller/commit/5abfcbcc1f792c354ea2bb91474b881946f5f8b9
