### ISSUE TITLE
提个意见

### ISSUE THREAD

**Issue by woodnaonly** [xinyihl/LiteLoaderQQNT-PluginInstaller#2]
![image_2024-04-28_19-03-33](https://github.com/xinyihl/LiteLoaderQQNT-PluginInstaller/assets/11649184/a8727ae4-fdb7-45ca-8eeb-79edb6a3c2ff)
提个建议，标题加个超链接到仓库，方便跳转。

**Comment by xinyihl** [comment]
感谢你的建议。 
已修改 @https://github.com/xinyihl/LiteLoaderQQNT-PluginInstaller/commit/693e88a4bf2b976a37932eebfa14b1440b3c99a5
