### ISSUE TITLE
[Bug] Linux 下未创建 data/plugininstaller 文件夹时无法正常下载

### ISSUE THREAD

**Issue by arenekosreal** [xinyihl/LiteLoaderQQNT-PluginInstaller#3]
https://github.com/xinyihl/LiteLoaderQQNT-PluginInstaller/blob/main/src/main_models/pluginApi.js#L38
这里似乎没有在文件夹不存在时创建文件夹的逻辑，所以在 Linux 下如果这个文件夹不存在，更内层的临时文件也会无法创建。

**Comment by daminoac** [comment]
Windows系统也会出现这个问题

**Comment by xinyihl** [comment]
fix at https://github.com/xinyihl/LiteLoaderQQNT-PluginInstaller/commit/31c4102b8c5111cd177ffe65cda2a6ce271a1147
