### ISSUE TITLE
安装插件提示链接格式错误

### ISSUE THREAD

**Issue by strange-qwq** [xinyihl/LiteLoaderQQNT-PluginInstaller#4]
尝试了以下几个变体都不行：
`llqqnt://plugininstaller/xinyihl/LiteLoaderQQNT-PluginInstaller/main/manifest.json`（文档内的）
`llqqnt://plugininstaller/xinyihl/LiteLoaderQQNT-PluginInstaller/blob/main/manifest.json`（GitHub内点击`manifest.json`文件打开的链接改前缀）
`https://github.com/xinyihl/LiteLoaderQQNT-PluginInstaller/main/manifest.json`（文档内的）
`https://github.com/xinyihl/LiteLoaderQQNT-PluginInstaller/blob/main/manifest.json`（GitHub内点击`manifest.json`文件打开的链接）

建议直接输入github仓库地址，自动拼接上路径

**Comment by xinyihl** [comment]
直接通过仓库地址不太现实，因为直接仓库地址没有分支信息
但是现在已经兼容大部分链接 https://github.com/xinyihl/LiteLoaderQQNT-PluginInstaller/commit/b612c93784625101507ff8f5c055e6380547593f
