### ISSUE TITLE
一直处于下载中

### ISSUE THREAD

**Issue by beilove** [xinyihl/LiteLoaderQQNT-PluginInstaller#5]
![image](https://github.com/xinyihl/LiteLoaderQQNT-PluginInstaller/assets/70726513/28f010b5-e917-4e05-b4d7-6b0a67b80828)
手动输入连接，或者点击https://xinyihl.github.io/LiteLoaderQQNT-PluginInstaller/ 安装，都会在下载后无响应

环境：Win11 专业版23H2 22631.3527
QQ版本: 9.9.9-23159 (64位)
![image](https://github.com/xinyihl/LiteLoaderQQNT-PluginInstaller/assets/70726513/54b3bedb-f874-4f2d-b065-591a6d3f7a5d)

**Comment by xinyihl** [comment]
抱歉这是我的问题，更新至最新版本就可以了。
