### ISSUE TITLE
插件更新点击检查后下面无内容

### ISSUE THREAD

**Issue by QQ804218** [xinyihl/LiteLoaderQQNT-PluginInstaller#6]
![微信截图_20240519093319](https://github.com/xinyihl/LiteLoaderQQNT-PluginInstaller/assets/67571282/762e6dec-8688-4328-aac6-1f1a60b910eb)

**Comment by xinyihl** [comment]
1. 所有启用的插件没有需要更新的（不会检测没启用的插件）
2. 你的网络问题无法访问github
3. 你的代理设置有问题（插件会自动读取并使用系统代理）
