### ISSUE TITLE
安装插件丢失node_modules

### ISSUE THREAD

**Issue by MUKAPP** [xinyihl/LiteLoaderQQNT-PluginInstaller#7]
是直接下的仓库吗？release里是有node_modules的
![image](https://github.com/xinyihl/LiteLoaderQQNT-PluginInstaller/assets/41848070/8ac9b42e-63ed-4161-8e76-abe14325e742)
![image](https://github.com/xinyihl/LiteLoaderQQNT-PluginInstaller/assets/41848070/526bc587-55ea-45a1-a692-b4011d9bf105)

**Comment by xinyihl** [comment]
优先通过github的api https://api.github.com/repos/[仓库]/releases/latest
获取的最新releases，如果这个api返回的不包含下载链接就下载仓库

**Comment by MUKAPP** [comment]
了解了，但是api是有限额的（）
我这应该就是到了限额才下的仓库
![image](https://github.com/xinyihl/LiteLoaderQQNT-PluginInstaller/assets/41848070/2d236b94-6176-40d6-8cb5-a3e54fe0746d)

**Comment by xinyihl** [comment]
嗯，但是我觉得正常使用应该不会触发限额
我看看考虑再加一个判断吧

**Comment by MUKAPP** [comment]
> 嗯，但是我觉得正常使用应该不会触发限额 我看看考虑再加一个判断吧

![image](https://github.com/xinyihl/LiteLoaderQQNT-PluginInstaller/assets/41848070/f7575ce8-e4c8-4309-8243-fa49ba53f586)
每小时也才60次（）大佬加油

**Comment by xinyihl** [comment]
change at https://github.com/xinyihl/LiteLoaderQQNT-PluginInstaller/commit/9fd0f5a5c72450ed9cda94fe2b872077d90957e6
