### ISSUE TITLE
安装插件时出现问题

### ISSUE THREAD

**Issue by LINKlang** [xinyihl/LiteLoaderQQNT-PluginInstaller#8]
![image](https://github.com/xinyihl/LiteLoaderQQNT-PluginInstaller/assets/116951234/7c3e9c90-9727-4169-973b-c891d6cf06d4)

安装`https://github.com/ltxhhz/LL-plugin-list-viewer`时出现的保存

版本信息
![image](https://github.com/xinyihl/LiteLoaderQQNT-PluginInstaller/assets/116951234/0def7641-9384-4f43-80bf-f6d03381c311)

**Comment by LINKlang** [comment]
尝试安装其他插件，貌似未出现问题

**Comment by xinyihl** [comment]
对方插件问题不会进行修复
