### ISSUE TITLE
无法安装和更新`插件列表查看`

### ISSUE THREAD

**Issue by letterk** [xinyihl/LiteLoaderQQNT-PluginInstaller#9]
![image](https://github.com/xinyihl/LiteLoaderQQNT-PluginInstaller/assets/9822709/31bcc0e9-5591-46e7-83ce-2a710e4b91bc)
https://github.com/ltxhhz/LL-plugin-list-viewer

**Comment by ltxhhz** [comment]
这个问题是因为插件的压缩包使用了反斜杠作为分隔符，`node-stream-zip` 在配置 `skipEntryNameValidation: false` 的情况下会对其进行检查，导致报错
